sudo: required 
language: node_js
node_js:
    - "stable"
env:
  global:
    CODECOV_TOKEN=$CODECOV_TOKEN
services: 
    - docker

before_install: 
    - npm install -g codecov
    - docker build -t wilpat/sample-app -f Dockerfile.dev .
script:     
    - npm run test -- --coverage && codecov

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "hello-world-react"
  env: "Helloworldreact-env"
  bucket_name: "react-helloworld"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"